services:
  - type: web
    name: client-angular
    env: docker
    plan: free
    repo: https://github.com/<YOUR_USERNAME>/<YOUR_REPO_NAME>
    branch: main
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - ./**
    autoDeploy: true
